site_name: Miro

nav:
  - About Miro: Miro.md
  - UI elements: elements.md
  - Adding a file to a board: file.md
  - Adding sticky notes to a board: sticky.md
  - Locking an object on a board: lock.md
  - Troubleshooting: trouble.md
  
  

theme:
  name: material
  logo: Images/logo.png
  favicon: Images/logo.png
  palette:
    primary: yellow
    accent: black
    
  
  font:
    text: Inter
  features:
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - search.share
    - search.suggest
    - header.autohide
    - navigation.footer
  

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences    

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  

 
